
###### Device name ######
esphome:
  name: ESP8266-AN01/DG01/SC01/DH01
  comment: ESP8266 AN01-Thermocouple/DG01-Digital/SC01-Display/DH01-Humidy
  friendly_name: Data Visualization

 ### Project info ###  
  project:
    name: "Phantom_Data_Visualization"
    version: "3.0 Betta"

###### Dev board and platform ######
esp8266:
  board: nodemcuv2



###### Data logger ######
logger:
    level: VERBOSE
  
###### Home Assistant's Native API Config ######
api:
  encryption:
    key: !secret api_password
  
###### MQTT Broker Config ######
mqtt:
  discovery: false
  broker: !secret mqtt_broker
  port: !secret mqtt_brokerport
#  keepalive: 5s
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery_prefix: homeassistant
  
###### Over-the-Air Updates ######
ota:
  password: !secret ota_password




###### Network Config ######
wifi:
  networks:
    - ssid: !secret wifi_ssid
      bssid: !secret wifi_bssid
      password: !secret wifi_password

    - ssid: !secret wifi_ssid2
      bssid: !secret wifi_bssid2
      password: !secret wifi_password2

    - ssid: !secret wifi_ssid3
      bssid: !secret wifi_bssid3
      password: !secret wifi_password3

      #### Static IP Address ####
   # manual_ip:
   #   static_ip: 192.168.254.170
   #   gateway: 192.168.254.1
   #   subnet: 255.255.128.0
   #   dns1: 192.168.254.4
   #   dns2: 192.168.254.1

      #### Other settings ####
  #  fast_connect: on
  #  power_save_mode: none
  
###### Access Point and Captive Portal Config ######
  ap:
    ssid: "esp32-dev-kit-template"
    password: !secret ap_password
  
captive_portal:
  



###### 'Ports' Config ######

### ST7735 TFT Screen ###
spi:
    clk_pin: GPIO18
    mosi_pin: GPIO23

dallas:
  - pin: GPIO22
    update_interval: 1s
  


  ####### Sensors #######
sensor:

### Dallas Temperature Sensors ###
#  - platform: dallas
#    address: 0x373c01f095e27428
#    name: "Sensor 1"
#    id: sondatemperatura1

### Home Assistant Entities (through Native API) ###
  - platform: homeassistant
    id: home_assistant_entity_id
    entity_id: sensor.sonoff_pow_r2_power
#    attribute: current_power
  



###### Screen (If needed) ######

### Fonts, Graphs and Colors ###
font:
    - file: "gfonts://Roboto"
      id: roboto
      size: 15
  
    - file: "gfonts://Roboto"
      id: roboto_big
      size: 35

###### ST7735 TFT Display Config (also check SPI pinout) ######
display:
    - platform: st7735
      model: "INITR_BLACKTAB"
      reset_pin: GPIO4
      cs_pin: GPIO5
      dc_pin: GPIO2
      rotation: 270
      device_width: 128
      device_height: 160
      col_start: 0
      row_start: 0
      eight_bit_color: True
      update_interval: 1000ms

      ###### Screen content ######
      lambda: |-
        it.print(15, 5, id(roboto), "Temperatura Thermocouple");
        it.printf(25, 50, id(roboto_big), "%.1f W", id(home_assistant_entity_id).state);



  #    lambda: |-
  #      // Write some text
  #      it.print(0, 0, id(roboto), "Phantom Systems");
  #      // Draw a circle in the middle of the display
  #      it.filled_circle(it.get_width() / 2, it.get_height() / 2, 20);